apiVersion: v1
kind: Service
metadata:
  name: "{{ template "harbor.portal" . }}"
  annotations:
{{- if .Values.portal.serviceAnnotations }}
{{ toYaml .Values.portal.serviceAnnotations | indent 4 }}
{{- end }}
  labels:
{{ include "harbor.labels" . | indent 4 }}
spec:
{{- if (eq .Values.expose.ingress.controller "gce") }}
  type: ClusterIP
{{- end }}
  ports:
    - port: 80
      targetPort: 80
  selector:
{{ include "harbor.matchLabels" . | indent 4 }}
    component: portal
