{{- $ingress := .Values.expose.ingress -}}
{{- $tls := .Values.expose.tls -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ template "harbor.ingress" . }}"
  labels:
{{ include "harbor.labels" . | indent 4 }}
  annotations:
{{ toYaml $ingress.annotations | indent 4 }}
spec:
  tls:
  - secretName: {{ $tls.certManagerGeneratedSecretForCore }}
    hosts:
    - {{ $ingress.hosts.core }}
  - secretName: {{ $tls.certManagerGeneratedSecretForNotary }}
    hosts:
    - {{ $ingress.hosts.notary }}
{{- if  eq .Values.expose.ingress.controller "gce" }}
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "harbor.portal" . }}
          servicePort: 80
      - path: /api/
        backend:
          serviceName: {{ template "harbor.core" . }}
          servicePort: 80
      - path: /service/
        backend:
          serviceName: {{ template "harbor.core" . }}
          servicePort: 80
      - path: /v2/
        backend:
          serviceName: {{ template "harbor.core" . }}
          servicePort: 80
      - path: /chartrepo/
        backend:
          serviceName: {{ template "harbor.core" . }}
          servicePort: 80
      - path: /c/
        backend:
          serviceName: {{ template "harbor.core" . }}
          servicePort: 80
    {{- if $ingress.hosts.core }}
    host: {{ $ingress.hosts.core }}
    {{- end }}
  {{- if .Values.notary.enabled }}
  - http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "harbor.notary-server" . }}
          servicePort: 4443
    {{- if $ingress.hosts.notary }}
    host: {{ $ingress.hosts.notary }}
    {{- end }}
  {{- end }}
{{- else }}
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "harbor.portal" . }}
          servicePort: 80
      - path: /api/
        backend:
          serviceName: {{ template "harbor.core" . }}
          servicePort: 80
      - path: /service/
        backend:
          serviceName: {{ template "harbor.core" . }}
          servicePort: 80
      - path: /v2/
        backend:
          serviceName: {{ template "harbor.core" . }}
          servicePort: 80
      - path: /chartrepo/
        backend:
          serviceName: {{ template "harbor.core" . }}
          servicePort: 80
      - path: /c/
        backend:
          serviceName: {{ template "harbor.core" . }}
          servicePort: 80
    {{- if $ingress.hosts.core }}
    host: {{ $ingress.hosts.core }}
    {{- end }}
  {{- if .Values.notary.enabled }}
  - http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "harbor.notary-server" . }}
          servicePort: 4443
    {{- if $ingress.hosts.notary }}
    host: {{ $ingress.hosts.notary }}
    {{- end }}
  {{- end }}
{{- end }}